-- Hyprland default apps

TERMINAL       = "alacritty"
TERMINAL_CLASS = "Alacritty"
FILE_MANAGER   = "dolphin"
BROWSER        = "firefox"
BROWSER_CLASS  = "firefox"
EDITOR         = "gnome-text-editor --new-window"
CALCULATOR     = "gnome-calculator"
NOTES          = "obsidian"
NOTES_CLASS    = "obsidian"
DISCORD        = "discord"
DISCORD_CLASS  = "discord"
EMAIL          = "/opt/outlook-for-linux/outlook-for-linux"
EMAIL_CLASS    = "outlook-for-linux"
